spring:
  application:
    name: job

  datasource:
    url: ${db.url}
    username: native
    password: native

  flyway:
    url: ${db.url}
    user: native
    password: native
    enabled: true
    postgresql:
      transactional-lock: false

db:
  url: jdbc:postgresql://localhost:5432/native
